<template>
  <a-modal
    v-model:open="visible"
    :title="$t('docModal.qaPairs')"
    width="920px"
    :footer="null"
    :destroy-on-close="true"
  >
    <div v-if="loading" class="qa-loading">
      <a-spin :tip="$t('docModal.loadingQa')" />
    </div>
    <a-alert v-else-if="errorMessage" type="error" show-icon :message="errorMessage" />
    <div v-else class="qa-shell">
      <div class="qa-toolbar">
        <span>{{ $t('docModal.bodyVersion', { version: payload?.cleaning_version ?? '-' }) }}</span>
        <span v-if="payload?.readonly">{{ $t('docModal.readonly') }}</span>
        <div v-if="!payload?.readonly" class="qa-toolbar-actions">
          <a-button :loading="actionLoading" @click="generate">{{ $t('docModal.autoGenerateDraft') }}</a-button>
          <a-button @click="startManual">{{ $t('docModal.manualAdd') }}</a-button>
          <a-button
            v-if="payload?.confirmable"
            type="primary"
            :disabled="confirmableItems.length === 0"
            :loading="actionLoading"
            @click="confirmAll"
          >
            {{ $t('docModal.batchConfirm') }}
          </a-button>
        </div>
      </div>
      <a-alert
        v-if="payload?.draft_mode"
        type="info"
        show-icon
        :message="$t('docModal.draftModeAlert')"
      />
      <a-alert
        v-if="draft"
        type="info"
        show-icon
        :message="$t('docModal.draftEvidenceAlert')"
      />
      <a-alert v-if="generationMessage" type="info" show-icon :message="generationMessage" />
      <section v-if="draft" class="qa-editor">
        <a-input
          v-model:value="draft.question"
          :maxlength="300"
          :placeholder="$t('docModal.questionPlaceholder')"
        />
        <a-textarea
          v-model:value="draft.answer"
          :maxlength="2000"
          :auto-size="{ minRows: 3, maxRows: 8 }"
          :placeholder="$t('docModal.answerPlaceholder')"
        />
        <div class="chunk-tags-editor">
          <a-tag
            v-for="(chunkId, index) in draft.source_chunk_ids"
            :key="`${chunkId}-${index}`"
            closable
            @close="removeChunkId(index)"
          >
            {{ chunkId }}
          </a-tag>
          <a-input
            v-model:value="chunkIdInput"
            :placeholder="$t('docModal.chunkIdPlaceholder')"
            @pressEnter="addChunkId"
            @blur="addChunkId"
          />
        </div>
        <div
          v-for="(evidence, index) in draft.evidence"
          :key="`evidence-${index}`"
          class="evidence-editor"
        >
          <a-input v-model:value="evidence.chunk_id" placeholder="chunk ID" />
          <a-textarea
            v-model:value="evidence.text"
            :auto-size="{ minRows: 2, maxRows: 5 }"
            :placeholder="$t('docModal.evidencePlaceholder')"
          />
          <a-button danger type="text" @click="draft.evidence.splice(index, 1)">{{ $t('docModal.deleteEvidence') }}</a-button>
        </div>
        <div class="qa-editor-actions">
          <a-button @click="draft.evidence.push({ chunk_id: '', text: '' })">{{ $t('docModal.addEvidence') }}</a-button>
          <a-button @click="draft = null">{{ $t('common.cancel') }}</a-button>
          <a-button type="primary" :loading="actionLoading" @click="saveDraft">{{ $t('docModal.saveDraft') }}</a-button>
        </div>
      </section>
      <a-empty v-if="!draft && items.length === 0" :description="$t('docModal.noQaPairs')" />
      <section v-for="item in items" :key="item.qa_id" class="qa-card">
        <header>
          <div class="qa-tags">
            <a-tag :color="item.source === 'manual' ? 'purple' : 'blue'">
              {{ $t(item.source === 'manual' ? 'docModal.manualSource' : 'docModal.autoSource') }}
            </a-tag>
            <a-tag :color="statusColor(item)">{{ statusLabel(item) }}</a-tag>
            <a-tag v-if="item.possibly_outdated" color="orange">{{ $t('docModal.bodyChangedReview') }}</a-tag>
          </div>
          <div v-if="!payload?.readonly" class="qa-card-actions">
            <a-button size="small" @click="edit(item)">{{ $t('common.edit') }}</a-button>
            <a-button
              v-if="
                payload?.confirmable &&
                (item.status !== 'confirmed' || item.sync_status !== 'synced')
              "
              size="small"
              type="primary"
              :loading="actionLoading"
              @click="confirmOne(item)"
            >
              {{ $t('docModal.confirmAndSync') }}
            </a-button>
            <a-button
              v-if="item.status === 'draft'"
              size="small"
              danger
              :loading="actionLoading"
              @click="rejectOne(item)"
            >
              {{ $t('docModal.reject') }}
            </a-button>
          </div>
        </header>
        <strong class="question">{{ item.question }}</strong>
        <p class="answer">{{ item.answer }}</p>
        <a-alert
          v-if="item.sync_status === 'failed'"
          type="error"
          show-icon
          :message="item.sync_error || $t('docModal.syncFailed')"
        />
        <div class="evidence-list">
          <div v-for="evidence in item.evidence" :key="`${item.qa_id}-${evidence.chunk_id}`">
            <code>{{ evidence.chunk_id }}</code>
            <span>{{ evidence.text }}</span>
          </div>
        </div>
      </section>
      <div class="qa-footer">
        <a-button @click="visible = false">{{ $t('common.close') }}</a-button>
      </div>
    </div>
  </a-modal>
</template>
<script setup>
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { message, Modal } from 'ant-design-vue'
import { documentApi } from '@/apis/knowledge_api'
const props = defineProps({
  open: { type: Boolean, default: false },
  kbId: { type: [String, Number], default: '' },
  fileId: { type: [String, Number], default: '' }
})
const emit = defineEmits(['update:open', 'changed'])
const { t } = useI18n()
const visible = computed({
  get: () => props.open,
  set: (value) => emit('update:open', value)
})
const loading = ref(false)
const actionLoading = ref(false)
const errorMessage = ref('')
const payload = ref(null)
const items = computed(() => payload.value?.items || [])
const confirmableItems = computed(() =>
  items.value.filter((item) => item.status === 'draft' || item.sync_status === 'failed')
)
const draft = ref(null)
const generationMessage = ref('')
const chunkIdInput = ref('')
const statusLabel = (item) => {
  if (item.sync_status === 'failed') return t('docModal.statusSyncFailed')
  return item.status === 'confirmed' ? t('docModal.statusConfirmed') : t('docModal.statusDraft')
}
const statusColor = (item) => {
  if (item.sync_status === 'failed') return 'red'
  return item.status === 'confirmed' ? 'green' : 'gold'
}
const load = async () => {
  if (!props.kbId || !props.fileId) return
  loading.value = true
  errorMessage.value = ''
  try {
    payload.value = await documentApi.getDocumentQAs(props.kbId, props.fileId)
  } catch (error) {
    errorMessage.value = error.message || t('docModal.loadQaFailed')
  } finally {
    loading.value = false
  }
}
const handleOpenChange = (open) => {
  if (open) load()
}
watch(() => props.open, handleOpenChange)
const startManual = () => {
  draft.value = {
    qa_id: null,
    version: null,
    question: '',
    answer: '',
    source_chunk_ids: [],
    evidence: [{ chunk_id: '', text: '' }]
  }
}
const addChunkId = () => {
  const value = String(chunkIdInput.value || '').trim()
  if (!value) return
  if (!draft.value?.source_chunk_ids?.includes(value)) {
    draft.value?.source_chunk_ids?.push(value)
  }
  chunkIdInput.value = ''
}
const removeChunkId = (index) => {
  draft.value?.source_chunk_ids?.splice(index, 1)
}
const edit = (item) => {
  draft.value = {
    qa_id: item.qa_id,
    version: item.version,
    question: item.question,
    answer: item.answer,
    source_chunk_ids: [...item.source_chunk_ids],
    evidence: item.evidence.map((evidence) => ({ ...evidence }))
  }
}
const runAction = async (action, successMessage) => {
  actionLoading.value = true
  try {
    await action()
    await load()
    message.success(successMessage)
    emit('changed')
  } catch (error) {
    message.error(error.message || t('docModal.operationFailedRetry'))
  } finally {
    actionLoading.value = false
  }
}
const saveDraft = async () => {
  const evidence = draft.value.evidence.filter((item) => item.chunk_id && item.text)
  const body = {
    question: draft.value.question,
    answer: draft.value.answer,
    source_chunk_ids: draft.value.source_chunk_ids,
    evidence
  }
  await runAction(async () => {
    if (draft.value.qa_id) {
      await documentApi.updateDocumentQA(props.kbId, props.fileId, draft.value.qa_id, {
        ...body,
        version: draft.value.version
      })
    } else {
      await documentApi.createDocumentQA(props.kbId, props.fileId, body)
    }
    draft.value = null
  }, t('docModal.qaDraftSaved'))
}
const generate = async () => {
  actionLoading.value = true
  try {
    const queued = await documentApi.generateDocumentQAs(props.kbId, props.fileId)
    generationMessage.value = queued.created
      ? t('docModal.generatingQaDraft')
      : t('docModal.generationTaskExists')
    for (let attempt = 0; attempt < 30 && visible.value; attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 1000))
      const task = await documentApi.getDocumentQAGenerationTask(
        props.kbId,
        props.fileId,
        queued.task_id
      )
      generationMessage.value = task.message || generationMessage.value
      if (task.status === 'success') {
        await load()
        generationMessage.value = ''
        message.success(t('docModal.qaDraftGenerated'))
        emit('changed')
        return
      }
      if (['failed', 'cancelled'].includes(task.status)) {
        generationMessage.value = task.error || t('docModal.qaDraftGenerationFailed')
        return
      }
    }
    generationMessage.value = t('docModal.qaTaskRunning')
  } catch (error) {
    message.error(error.message || t('docModal.generationFailedRetry'))
  } finally {
    actionLoading.value = false
  }
}
const confirmOne = (item) =>
  runAction(
    () => documentApi.confirmDocumentQA(props.kbId, props.fileId, item.qa_id, item.version),
    t('docModal.qaConfirmed')
  )
const confirmAll = () =>
  runAction(
    () =>
      documentApi.batchConfirmDocumentQAs(
        props.kbId,
        props.fileId,
        confirmableItems.value.map((item) => ({ qa_id: item.qa_id, version: item.version }))
      ),
    t('docModal.qaBatchConfirmed')
  )
const rejectOne = (item) => {
  Modal.confirm({
    title: t('docModal.rejectDraftTitle'),
    content: t('docModal.rejectDraftContent'),
    okText: t('docModal.confirmReject'),
    cancelText: t('common.cancel'),
    onOk: () =>
      runAction(
        () => documentApi.rejectDocumentQA(props.kbId, props.fileId, item.qa_id, item.version),
        t('docModal.qaDraftRejected')
      )
  })
}
</script>
<style scoped lang="less">
.qa-loading {
  display: grid;
  min-height: 360px;
  place-items: center;
}
.qa-shell,
.qa-editor,
.qa-card {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.chunk-tags-editor {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
}
.chunk-tags-editor .ant-input {
  flex: 1;
  min-width: 240px;
}
.qa-toolbar,
.qa-card header,
.qa-editor-actions,
.qa-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
}
.qa-toolbar {
  color: var(--color-text-secondary);
}
.qa-toolbar-actions,
.qa-card-actions,
.qa-tags {
  display: flex;
  gap: 8px;
}
.qa-editor,
.qa-card {
  padding: 16px;
  border: 1px solid var(--gray-150);
  border-radius: 8px;
  background: var(--gray-0);
}
.evidence-editor,
.evidence-list > div {
  display: grid;
  grid-template-columns: minmax(140px, 220px) 1fr auto;
  gap: 8px;
  align-items: start;
}
.question,
.answer {
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
.answer {
  margin: 0;
}
.evidence-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  color: var(--color-text-secondary);
}
.evidence-list code {
  overflow-wrap: anywhere;
}
.qa-footer {
  justify-content: flex-end;
}
</style>
